### ISSUE TITLE
Line Contains Inconsistent Indentation

### ISSUE THREAD

**Issue by timcosta** [slb235/vscode-coffeelint#1]
First, of all, thanks for the coffeelint vscode plugin - been waiting for one forever.

One possible bug is that it seems to randomly tag some of my lines as having inconsistent indentation when I know for a fact there are only four spaces between the gutter and the beginning of the line. I had to uninstall the extension because it was falsely highlighting half of my files, and i'm looking forward to this getting fixed.

**Comment by slb235** [comment]
Hey tjsail33,

does this differ from what the command line coffeelint returns? Have you got an example of a file where that happens?

**Comment by timcosta** [comment]
Sorry for the delay, had broken my email notification preferences which are now fixed. It appears the CLI version also has the same errors - i assume I just need a coffeelint prefs file. Sorry!
